version: '2'

services:

### PHP-FPM Container #######################################

  php-fpm:
      build:
          context: ./php-fpm
          dockerfile: Dockerfile # Change this if you wanna use another PHP version
      volumes_from:
          - application
      expose:
          - "9000"
      links:
          - workspace

### Application Code Container ######################

  application:
      build: ./application
      volumes:
          - ../:/var/www

### Databases Data Container ################################

  data:
      build: ./data
      volumes:
          - /var/lib/mysql
          - /var/lib/mariadb
          - /var/lib/redis
          - /var/lib/memcached

### Nginx Server Container ##################################

  nginx:
      build: ./nginx
      volumes_from:
          - application
      volumes:
          - ./logs/nginx/:/var/log/nginx
      ports:
          - "80:80"
          - "443:443"
      links:
          - php-fpm

### MySQL Container #########################################

  mysql:
      build: ./mysql
      volumes_from:
          - data
      ports:
          - "3306:3306"
      environment:
          MYSQL_DATABASE: app_db
          MYSQL_USER: app_user
          MYSQL_PASSWORD: 123456
          MYSQL_ROOT_PASSWORD: 123456
      links:
          - php-fpm
          - phpmyadmin

### MariaDB Container #######################################

  mariadb:
      build: ./mariadb
      volumes_from:
          - data
      ports:
          - "3306:3306"
      environment:
          MYSQL_DATABASE: app_db
          MYSQL_USER: app_user
          MYSQL_PASSWORD: 123456
          MYSQL_ROOT_PASSWORD: 123456
      links:
          - php-fpm

### Redis Container #########################################

  redis:
      build: ./redis
      volumes_from:
          - data
      ports:
          - "6379:6379"
      links:
          - php-fpm

### Memcached Container #####################################

  memcached:
      build: ./memcached
      volumes_from:
          - data
      ports:
          - "11211:11211"
      links:
          - php-fpm

### PHPMyAdmin ##############################################

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      environment:
          - PMA_ARBITRARY=1
      ports:
          - "8080:80"

### Workspace Utilities Container ###########################

  workspace:
      build: ./workspace
      volumes_from:
          - application
      tty: true

### Add more Containers below ###############################
